// Every quest, by land: each is done once. The notice board in a land's camp offers that land's quests (its
// dungeons' too) as the hero's level allows and earlier ones are done (after); any board takes them back for
// the reward. Plain data.
//   goal: kill (a monster type, or a family: slime, bandit, cultist, skeleton, frostborn, ashen, shade, dread…),
//         collect (things that drop from them while the quest is on: item, from, chance), visit (a place or a
//         zone), talk (to someone in a camp), learn (spend a skill point), equip (an item of a slot or a class
//         of items), upgrade (anything to +n), bank (put something in the bank), buy (from a merchant)
//   w: how much it's worth (XP and gold grow with it and the quest's level); reward: what else it gives:
//      items [[key, n]], gear (the best of the hero's class's: { kind, level }), recipes [[key, n]]
//   zone: where its dashed ring goes on the minimap
const Q = (land, list) => list.map((q) => ({ land, w: 1, ...q, min: Math.max(1, q.min ?? q.level - 2) }));

export const QUESTS = [
  ...Q('emberwood', [
    { id: 'ew_meadow', level: 1, min: 1, title: 'Slimes in the Meadow', text: 'Slimes have overrun the meadow north of camp. Thin them out.', goal: { kind: 'kill', family: 'slime', count: 6 }, zone: 'meadow', reward: { items: [['hp_potion_1', 5]] } },
    { id: 'ew_skill', level: 1, min: 1, after: ['ew_meadow'], w: 0.5, title: 'A Hero in Training', text: 'Every hero grows in their own way. Open your skills (K, or the Skills button) and put a point into a tree.', goal: { kind: 'learn', count: 1 }, reward: { items: [['mp_potion_1', 4]] } },
    { id: 'ew_gel', level: 2, after: ['ew_meadow'], title: 'Slime Gel for Pip', text: 'Pip the provisioner brews potions from slime gel. Bring back five globs.', goal: { kind: 'collect', item: 'Slime Gel', from: 'slime', chance: 0.55, count: 5 }, zone: 'meadow', reward: { items: [['hp_potion_1', 5]] } },
    { id: 'ew_helmet', level: 2, after: ['ew_meadow'], w: 0.6, title: 'Dressed for Battle', text: 'A hero without a helmet is a hero with a headache. Hilda the armorer sells them: wear one.', goal: { kind: 'equip', slot: 'head', count: 1 }, reward: { gold: 40 } },
    { id: 'ew_pond', level: 2, after: ['ew_meadow'], title: 'The Mirror Pond', text: 'Bog slimes crowd the shore of the pond to the west. Clear them away.', goal: { kind: 'kill', type: 'slime_blue', count: 6 }, zone: 'pond' },
    { id: 'ew_bandits', level: 3, after: ['ew_pond'], title: 'The Bandit Hideout', text: 'Bandits camp to the north-east and raid our supplies. Drive them off.', goal: { kind: 'kill', family: 'bandit', count: 6 }, zone: 'bandits' },
    { id: 'ew_pouches', level: 3, after: ['ew_bandits'], title: 'Stolen Goods', text: 'The bandits carry what they stole in little pouches. Win back five of them.', goal: { kind: 'collect', item: 'Stolen Pouch', from: 'bandit', chance: 0.45, count: 5 }, zone: 'bandits', reward: { gear: { kind: 'hands', level: 1 } } },
    { id: 'ew_bank', level: 3, after: ['ew_bandits'], w: 0.5, title: 'Safekeeping', text: 'Oswin the banker keeps what you leave with him for every hero of yours. Put something in the bank.', goal: { kind: 'bank', count: 1 } },
    { id: 'ew_cultists', level: 4, after: ['ew_bandits'], title: 'Whispers in the Stones', text: 'Cultists chant among the standing stones to the north-west. Silence them.', goal: { kind: 'kill', family: 'cultist', count: 5 }, zone: 'stones' },
    { id: 'ew_sigils', level: 4, after: ['ew_cultists'], title: 'Cult Sigils', text: 'Each cultist wears a sigil of the thing they pray to. Bring four, so we know what it is.', goal: { kind: 'collect', item: 'Cultist Sigil', from: 'cultist', chance: 0.5, count: 4 }, zone: 'stones', reward: { gear: { kind: 'feet', level: 1 } } },
    { id: 'ew_magma', level: 4, after: ['ew_cultists'], title: 'Magma Slimes', text: 'Something has made the slimes by the stones burn. Put out four magma slimes.', goal: { kind: 'kill', type: 'slime_red', count: 4 }, zone: 'stones' },
    { id: 'ew_graveyard', level: 5, after: ['ew_cultists'], title: 'The Restless Dead', text: 'The dead are rising in the graveyard south of camp. Put them back to rest.', goal: { kind: 'kill', family: 'skeleton', count: 10 }, zone: 'graveyard' },
    { id: 'ew_dust', level: 6, after: ['ew_graveyard'], title: 'Bone Dust', text: 'Brom wants bone dust for his quenching bath. Grind six skeletons down for it.', goal: { kind: 'collect', item: 'Bone Dust', from: 'skeleton', chance: 0.5, count: 6 }, zone: 'graveyard', reward: { recipes: [['recipe_low', 1]] } },
    { id: 'ew_arena', level: 5, min: 5, after: ['ew_graveyard'], w: 0.5, title: 'Blood and Sand', text: 'The waystone in camp also reaches the Arena, where heroes test themselves against each other. Go and see it.', goal: { kind: 'visit', map: 'arena', count: 1 } },
    { id: 'ew_grok', level: 6, after: ['ew_graveyard'], w: 2.5, title: 'Grok the Brute', text: "Grok's lair lies at the far north end of the woods. End his reign.", goal: { kind: 'kill', type: 'brute', count: 1 }, zone: 'lair', reward: { recipes: [['recipe_low', 2]] } },
    { id: 'ew_upgrade', level: 6, after: ['ew_grok'], w: 0.8, title: "Brom's Anvil", text: 'Brom the blacksmith upgrades gear with recipes, and it never fails. Have him make something of yours +2.', goal: { kind: 'upgrade', plus: 2, count: 1 } },
    { id: 'ew_crypt', level: 7, after: ['ew_grok'], w: 0.7, title: 'The Crypt Below', text: 'The dead keep rising. Go down through the crypt door at the east end of the graveyard.', goal: { kind: 'visit', map: 'crypt', count: 1 }, zone: 'crypt' },
    { id: 'ew_mages', level: 8, after: ['ew_crypt'], title: 'Unholy Rites', text: 'Skeleton mages raise their brothers in the crypt. Destroy four.', goal: { kind: 'kill', type: 'skeleton_mage', count: 4 }, zone: 'crypt' },
    { id: 'ew_lich', level: 9, after: ['ew_crypt'], w: 3, title: 'Morvain the Lich', text: 'At the heart of the crypt Morvain the Lich calls the dead from their graves. Destroy him.', goal: { kind: 'kill', type: 'lich', count: 1 }, zone: 'crypt', reward: { gear: { kind: 'weapon', level: 10 } } },
    { id: 'ew_frostfang', level: 9, min: 8, after: ['ew_grok'], w: 0.6, title: 'Beyond the Waystone', text: 'The waystone in camp reaches the snowfields of Frostfang. Travel there and see the outpost.', goal: { kind: 'visit', map: 'frostfang', count: 1 } },
    { id: 'ew_deep', level: 11, min: 10, after: ['ew_lich'], w: 0.8, title: 'Deeper Still', text: 'Behind Morvain\'s throne the stairs go further down, to the Bone Pits. Go down.', goal: { kind: 'visit', map: 'crypt2', count: 1 }, zone: 'crypt_deep' },
    { id: 'ew_colossus', level: 13, after: ['ew_deep'], w: 3, title: 'The Bone Colossus', text: 'In the Bone Pits the dead have built something huge out of themselves. Bring it down.', goal: { kind: 'kill', type: 'bone_colossus', count: 1 }, zone: 'crypt_deep', reward: { recipes: [['recipe_low', 2]] } },
    { id: 'ew_wanderer', level: 12, min: 10, after: ['ew_grok'], w: 3, title: 'The Wanderer', text: 'Now and then Gorehorn the Wanderer roams Emberwood, minding his own business. He is very hard to kill and carries rare things. Bring friends.', goal: { kind: 'kill', type: 'gorehorn', count: 1 }, reward: { recipes: [['recipe_low', 2]] } },
  ]),
  ...Q('frostfang', [
    { id: 'ff_outpost', level: 10, min: 8, w: 0.6, title: 'The Frozen North', text: 'Sigrun the weaponsmith runs the outpost. Go and say hello.', goal: { kind: 'talk', role: 'weapons', land: 'frostfang', count: 1 } },
    { id: 'ff_ooze', level: 10, after: ['ff_outpost'], title: 'Cold Ooze', text: 'Frost slimes creep through the snowfields. Clear eight of them.', goal: { kind: 'kill', type: 'slime_frost', count: 8 }, zone: 'ff_fields' },
    { id: 'ff_scouts', level: 11, after: ['ff_outpost'], title: 'Eyes in the Snow', text: 'Frostborn scouts watch the outpost. Put out their eyes: six of them.', goal: { kind: 'kill', type: 'frost_scout', count: 6 }, zone: 'ff_fields' },
    { id: 'ff_furs', level: 12, after: ['ff_scouts'], title: 'Furs for the Outpost', text: 'The raiders wear good furs and the outpost is cold. Bring six.', goal: { kind: 'collect', item: 'Raider Fur', from: 'frostborn', chance: 0.45, count: 6 }, zone: 'ff_raiders', reward: { items: [['hp_potion_1', 10]] } },
    { id: 'ff_raiders', level: 13, after: ['ff_scouts'], title: 'Raider Encampment', text: 'The Frostborn gather in their camp to the west. Break the war band: ten of them.', goal: { kind: 'kill', family: 'frostborn', count: 10 }, zone: 'ff_raiders' },
    { id: 'ff_witches', level: 14, after: ['ff_raiders'], title: 'Ice Witches', text: 'Ice witches curse the raiders\' blades. Silence four.', goal: { kind: 'kill', type: 'ice_witch', count: 4 }, zone: 'ff_raiders' },
    { id: 'ff_lake', level: 15, after: ['ff_raiders'], w: 0.6, title: 'The Frozen Lake', text: 'Something stirs under the ice of the lake to the east. Go and look.', goal: { kind: 'visit', zone: 'ff_lake', count: 1 }, zone: 'ff_lake' },
    { id: 'ff_cores', level: 15, after: ['ff_lake'], title: 'Glacial Cores', text: 'The glacial slimes of the lake carry hearts of ice. Elka the provisioner wants five.', goal: { kind: 'collect', item: 'Glacial Core', from: 'slime_glacial', chance: 0.55, count: 5 }, zone: 'ff_lake', reward: { items: [['mp_potion_2', 6]] } },
    { id: 'ff_frostbone', level: 16, after: ['ff_lake'], title: 'Frostbone Warriors', text: 'Skeletons in ice walk the lake shore. Shatter six.', goal: { kind: 'kill', type: 'frostbone', count: 6 }, zone: 'ff_lake' },
    { id: 'ff_upgrade', level: 17, after: ['ff_frostbone'], w: 0.8, title: 'Tempered', text: 'The cold makes steel brittle; Brom\'s anvil in Emberwood makes it strong. Bring something of yours to +4.', goal: { kind: 'upgrade', plus: 4, count: 1 } },
    { id: 'ff_archers', level: 18, after: ['ff_frostbone'], title: 'Arrows from the Ridge', text: 'Frost archers shoot at anything that climbs the Howling Ridge. Stop six.', goal: { kind: 'kill', type: 'frost_archer', count: 6 }, zone: 'ff_ridge' },
    { id: 'ff_berserkers', level: 19, after: ['ff_archers'], title: 'Berserkers', text: 'The jarl\'s berserkers guard the ridge. Cut down five.', goal: { kind: 'kill', type: 'raider_berserker', count: 5 }, zone: 'ff_ridge' },
    { id: 'ff_horns', level: 19, after: ['ff_archers'], title: 'War Horns', text: 'When the horns blow, the raiders come. Take four from the berserkers.', goal: { kind: 'collect', item: 'Raider War Horn', from: 'raider_berserker', chance: 0.4, count: 4 }, zone: 'ff_ridge', reward: { gear: { kind: 'weapon', level: 20 } } },
    { id: 'ff_mid', level: 20, after: ['ff_berserkers'], w: 0.6, title: 'Middle Class', text: 'From level 20 merchants sell middle class gear. Wear a middle class item.', goal: { kind: 'equip', tier: 'mid', count: 1 } },
    { id: 'ff_jarl', level: 21, after: ['ff_berserkers'], w: 2.5, title: 'Hrimgar the Frost Jarl', text: 'The raiders answer to Hrimgar, who holds court at the far end of Frostfang. Take his hold.', goal: { kind: 'kill', type: 'frost_jarl', count: 1 }, zone: 'ff_hold', reward: { recipes: [['recipe_low', 2]] } },
    { id: 'ff_rimeheart', level: 20, after: ['ff_jarl'], w: 0.7, title: 'Below the Ice', text: 'A cave mouth in the eastern hills breathes cold air. Go down into Rimeheart Caverns.', goal: { kind: 'visit', map: 'rimeheart', count: 1 }, zone: 'rimeheart' },
    { id: 'ff_tombs', level: 22, after: ['ff_rimeheart'], title: 'The Frozen Tombs', text: 'The caverns are full of the frozen dead. Shatter eight frostbone warriors down there.', goal: { kind: 'kill', type: 'frostbone', count: 8 }, zone: 'rimeheart' },
    { id: 'ff_rimeking', level: 24, after: ['ff_rimeheart'], w: 3, title: 'The Rime King', text: 'Vorrak the Rime King raises the frozen dead from his throne. End him.', goal: { kind: 'kill', type: 'rime_king', count: 1 }, zone: 'rimeheart', reward: { recipes: [['recipe_mid', 1]] } },
    { id: 'ff_deep', level: 25, min: 24, after: ['ff_rimeking'], w: 0.8, title: 'The Frozen Deep', text: 'Below Vorrak\'s throne the caverns go deeper. Follow them.', goal: { kind: 'visit', map: 'rimeheart2', count: 1 }, zone: 'rime_deep' },
    { id: 'ff_ymira', level: 28, after: ['ff_deep'], w: 3, title: 'Ymira of the Deep', text: 'Ymira, the witch who taught the jarl\'s witches, waits in the Frozen Deep. Melt her heart.', goal: { kind: 'kill', type: 'ymira', count: 1 }, zone: 'rime_deep', reward: { recipes: [['recipe_mid', 2]] } },
    { id: 'ff_giant', level: 22, min: 18, after: ['ff_jarl'], w: 3, title: 'The Frost Giant', text: 'Skadi the Frost Giant walks the snowfields now and then. She is slow to anger and terrible when angered. Bring a party.', goal: { kind: 'kill', type: 'skadi', count: 1 }, reward: { recipes: [['recipe_low', 3]] } },
    { id: 'ff_onward', level: 22, min: 20, after: ['ff_jarl'], w: 0.6, title: 'Ash on the Wind', text: 'The waystones reach on, to the burning wastes of Cinderfall. Travel there.', goal: { kind: 'visit', map: 'cinderfall', count: 1 } },
  ]),
  ...Q('cinderfall', [
    { id: 'cf_bastion', level: 22, min: 20, w: 0.6, title: 'Ashguard Bastion', text: 'Kael the weaponsmith keeps the bastion\'s forge going. Go and find him.', goal: { kind: 'talk', role: 'weapons', land: 'cinderfall', count: 1 } },
    { id: 'cf_slimes', level: 22, after: ['cf_bastion'], title: 'Cinder Slimes', text: 'Slimes full of embers roll across the Ashen Flats. Put out eight.', goal: { kind: 'kill', type: 'slime_cinder', count: 8 }, zone: 'cf_flats' },
    { id: 'cf_embers', level: 23, after: ['cf_slimes'], title: 'Embers in a Jar', text: 'Mira the provisioner keeps living embers to brew with. Catch six from the cinder slimes.', goal: { kind: 'collect', item: 'Living Ember', from: 'slime_cinder', chance: 0.55, count: 6 }, zone: 'cf_flats', reward: { items: [['hp_potion_2', 8]] } },
    { id: 'cf_bandits', level: 24, after: ['cf_bastion'], title: 'Ash Bandits', text: 'Ash bandits rob anyone crossing the flats. Defeat eight.', goal: { kind: 'kill', type: 'ash_bandit', count: 8 }, zone: 'cf_flats' },
    { id: 'cf_obsidian', level: 26, after: ['cf_bandits'], w: 0.6, title: 'Obsidian Fields', text: 'To the east the ground is black glass. Go and see what the cult builds there.', goal: { kind: 'visit', zone: 'cf_obsidian', count: 1 }, zone: 'cf_obsidian' },
    { id: 'cf_cultists', level: 27, after: ['cf_obsidian'], title: 'The Cinder Cult', text: 'Cinder cultists call fire from the sky over the obsidian fields. Stop six.', goal: { kind: 'kill', type: 'cinder_cultist', count: 6 }, zone: 'cf_obsidian' },
    { id: 'cf_knights', level: 28, after: ['cf_obsidian'], title: 'Ash Knights', text: 'Knights of a fallen order guard the cult. Defeat six.', goal: { kind: 'kill', type: 'ash_knight', count: 6 }, zone: 'cf_obsidian' },
    { id: 'cf_shards', level: 29, after: ['cf_knights'], title: 'Obsidian Shards', text: 'The ash knights carry shards of obsidian as charms. Brann the armorer wants six for his work.', goal: { kind: 'collect', item: 'Obsidian Shard', from: 'ash_knight', chance: 0.45, count: 6 }, zone: 'cf_obsidian', reward: { gear: { kind: 'head', level: 20 } } },
    { id: 'cf_lava', level: 31, after: ['cf_knights'], w: 0.6, title: 'Lava Rivers', text: 'West of the bastion the lava runs in rivers. Something hulking lives there. Scout it out.', goal: { kind: 'visit', zone: 'cf_lava', count: 1 }, zone: 'cf_lava' },
    { id: 'cf_brutes', level: 31, after: ['cf_lava'], title: 'Molten Brutes', text: 'Brutes with molten skin wade in the lava. Bring down five.', goal: { kind: 'kill', type: 'molten_brute', count: 5 }, zone: 'cf_lava' },
    { id: 'cf_skeletons', level: 32, after: ['cf_lava'], title: 'Ember Skeletons', text: 'Skeletons with burning eyes dance around the lava pools. Break eight.', goal: { kind: 'kill', type: 'ember_skeleton', count: 8 }, zone: 'cf_lava' },
    { id: 'cf_upgrade', level: 33, after: ['cf_brutes'], w: 0.8, title: "The Smith's Art", text: 'Middle class steel takes middle class recipes. Have Brom bring something of yours to +5.', goal: { kind: 'upgrade', plus: 5, count: 1 } },
    { id: 'cf_archers', level: 35, after: ['cf_skeletons'], title: 'Pyre Archers', text: 'Fire arrows rain down from the Burning Ridge. Silence six pyre archers.', goal: { kind: 'kill', type: 'pyre_archer', count: 6 }, zone: 'cf_ridge' },
    { id: 'cf_wardens', level: 36, after: ['cf_archers'], title: 'Flame Wardens', text: 'Undead wardens keep the fires of the ridge burning. Put out five.', goal: { kind: 'kill', type: 'flame_warden', count: 5 }, zone: 'cf_ridge' },
    { id: 'cf_runes', level: 36, after: ['cf_archers'], title: 'Fire Runes', text: 'The wardens\' staves are carved with runes of fire. Bring five, before they burn more.', goal: { kind: 'collect', item: 'Fire Rune', from: 'flame_warden', chance: 0.45, count: 5 }, zone: 'cf_ridge', reward: { gear: { kind: 'weapon', level: 30 } } },
    { id: 'cf_king', level: 38, after: ['cf_wardens'], w: 2.5, title: 'Vulkhar the Ashen King', text: 'Vulkhar the Ashen King sits on his throne between the fire pits. Cast him down.', goal: { kind: 'kill', type: 'ashen_king', count: 1 }, zone: 'cf_throne', reward: { recipes: [['recipe_mid', 2]] } },
    { id: 'cf_forge', level: 38, after: ['cf_king'], w: 0.7, title: 'The Molten Forge', text: 'The forge in the east hills still burns, deep under the ground. Go in.', goal: { kind: 'visit', map: 'forge', count: 1 }, zone: 'forge' },
    { id: 'cf_kaldur', level: 42, after: ['cf_forge'], w: 3, title: 'Quench the Forge', text: 'Forgemaster Kaldur still arms the wastes from the Molten Forge. Put out his fires.', goal: { kind: 'kill', type: 'forgemaster', count: 1 }, zone: 'forge', reward: { recipes: [['recipe_mid', 2]] } },
    { id: 'cf_core', level: 43, min: 42, after: ['cf_kaldur'], w: 0.8, title: 'The Magma Core', text: 'Under the great forge there is a deeper fire. Follow the stairs down.', goal: { kind: 'visit', map: 'forge2', count: 1 }, zone: 'forge_deep' },
    { id: 'cf_magmaborn', level: 46, after: ['cf_core'], w: 3, title: 'The Magmaborn', text: 'In the core, molten rock has stood up and walks. Make it lie down again.', goal: { kind: 'kill', type: 'magmaborn', count: 1 }, zone: 'forge_deep', reward: { recipes: [['recipe_high', 1]] } },
    { id: 'cf_ignis', level: 40, min: 36, after: ['cf_king'], w: 3, title: 'The Living Pyre', text: 'Ignis, the Living Pyre, wanders the wastes now and then, burning whatever angers it. Bring a party, and the unique things it carries are yours.', goal: { kind: 'kill', type: 'ignis', count: 1 }, reward: { recipes: [['recipe_mid', 3]] } },
    { id: 'cf_onward', level: 40, min: 38, after: ['cf_king'], w: 0.6, title: 'Into the Dusk', text: 'The last waystone opens on Shadowmere, a marsh where the dead walk at twilight. Travel there.', goal: { kind: 'visit', map: 'shadowmere', count: 1 } },
  ]),
  ...Q('shadowmere', [
    { id: 'sm_duskwatch', level: 40, min: 38, w: 0.6, title: 'Duskwatch', text: 'Vesna the weaponsmith keeps watch at the edge of the marsh. Report to her.', goal: { kind: 'talk', role: 'weapons', land: 'shadowmere', count: 1 } },
    { id: 'sm_high', level: 40, after: ['sm_duskwatch'], w: 0.6, title: 'High Class', text: 'From level 40 merchants sell high class gear. Wear a high class item.', goal: { kind: 'equip', tier: 'high', count: 1 } },
    { id: 'sm_slimes', level: 40, after: ['sm_duskwatch'], title: 'Void Slimes', text: 'Slimes full of nothing ooze through the Gloom Marsh. Clear eight.', goal: { kind: 'kill', type: 'slime_void', count: 8 }, zone: 'sm_marsh' },
    { id: 'sm_essence', level: 41, after: ['sm_slimes'], title: 'Void Essence', text: 'Lyra the provisioner wants to know what the void slimes are made of. Bring six drops of their essence.', goal: { kind: 'collect', item: 'Void Essence', from: 'slime_void', chance: 0.55, count: 6 }, zone: 'sm_marsh', reward: { items: [['hp_potion_3', 6]] } },
    { id: 'sm_lurkers', level: 42, after: ['sm_duskwatch'], title: 'Bog Lurkers', text: 'Lurkers wait in the black water for anyone who wanders off the path. Defeat eight.', goal: { kind: 'kill', type: 'bog_lurker', count: 8 }, zone: 'sm_marsh' },
    { id: 'sm_wraithwood', level: 44, after: ['sm_lurkers'], w: 0.6, title: 'Wraithwood', text: 'West of Duskwatch there is a graveyard among dead trees. Go and look.', goal: { kind: 'visit', zone: 'sm_wraith', count: 1 }, zone: 'sm_wraith' },
    { id: 'sm_wraiths', level: 45, after: ['sm_wraithwood'], title: 'Wraiths', text: 'Wraiths drift among the graves of Wraithwood. Lay six to rest.', goal: { kind: 'kill', type: 'wraith', count: 6 }, zone: 'sm_wraith' },
    { id: 'sm_lanterns', level: 46, after: ['sm_wraiths'], title: 'Grave Lanterns', text: 'The wraiths carry little lanterns with the souls they took. Free five.', goal: { kind: 'collect', item: 'Grave Lantern', from: 'wraith', chance: 0.45, count: 5 }, zone: 'sm_wraith', reward: { gear: { kind: 'hands', level: 40 } } },
    { id: 'sm_knights', level: 46, after: ['sm_wraithwood'], title: 'Death Knights', text: 'Death knights march out of Wraithwood toward Duskwatch. Stop six.', goal: { kind: 'kill', type: 'death_knight', count: 6 }, zone: 'sm_wraith' },
    { id: 'sm_bones', level: 49, after: ['sm_knights'], title: 'The Bone Fields', text: 'In the fields of bones east of the path, the dread dead rise by the dozen. Break ten.', goal: { kind: 'kill', family: 'dread', count: 10 }, zone: 'sm_bones' },
    { id: 'sm_upgrade', level: 50, after: ['sm_bones'], w: 0.8, title: 'Masterwork', text: 'Only masterwork gear lasts in Shadowmere. Have Brom bring something of yours to +6.', goal: { kind: 'upgrade', plus: 6, count: 1 } },
    { id: 'sm_spire', level: 52, after: ['sm_bones'], w: 0.6, title: 'The Spire of Night', text: 'A dark spire rises in the south-west. Something gathers there. Go and see.', goal: { kind: 'visit', zone: 'sm_spire', count: 1 }, zone: 'sm_spire' },
    { id: 'sm_stalkers', level: 53, after: ['sm_spire'], title: 'Night Stalkers', text: 'Night stalkers hunt around the spire. Hunt six of them first.', goal: { kind: 'kill', type: 'night_stalker', count: 6 }, zone: 'sm_spire' },
    { id: 'sm_archers', level: 54, after: ['sm_spire'], title: 'Shadow Archers', text: 'Shadow archers guard the spire. Silence six.', goal: { kind: 'kill', type: 'shadow_archer', count: 6 }, zone: 'sm_spire' },
    { id: 'sm_shards', level: 54, after: ['sm_stalkers'], title: 'Night Shards', text: 'The stalkers wear shards of the spire itself. Bring five back to Duskwatch.', goal: { kind: 'collect', item: 'Night Shard', from: 'night_stalker', chance: 0.45, count: 5 }, zone: 'sm_spire', reward: { gear: { kind: 'weapon', level: 50 } } },
    { id: 'sm_hollow', level: 56, after: ['sm_archers'], w: 2.5, title: 'Malakar the Hollow King', text: 'Malakar the Hollow King commands the dead of Shadowmere from his throne of bones. Shatter him.', goal: { kind: 'kill', type: 'hollow_king', count: 1 }, zone: 'sm_throne', reward: { recipes: [['recipe_high', 2]] } },
    { id: 'sm_vault', level: 56, after: ['sm_hollow'], w: 0.7, title: 'The Abyssal Vault', text: 'A vault of black stone opens in the far east of the marsh. Go down.', goal: { kind: 'visit', map: 'abyss', count: 1 }, zone: 'abyss' },
    { id: 'sm_nyxara', level: 60, after: ['sm_vault'], w: 3, title: 'The Queen of the Abyss', text: 'At the bottom of the Abyssal Vault waits Nyxara, Queen of the Abyss, who began all of this. Finish it.', goal: { kind: 'kill', type: 'abyss_queen', count: 1 }, zone: 'abyss', reward: { recipes: [['recipe_high', 2]] } },
    { id: 'sm_below', level: 60, min: 58, after: ['sm_nyxara'], w: 0.8, title: 'The Void Below', text: 'Nyxara was not the bottom of everything. The stairs go further down.', goal: { kind: 'visit', map: 'abyss2', count: 1 }, zone: 'abyss_deep' },
    { id: 'sm_herald', level: 60, after: ['sm_below'], w: 3, title: 'The Void Herald', text: 'Whatever Nyxara served speaks through its herald, deep in the void. Silence it, for now.', goal: { kind: 'kill', type: 'void_herald', count: 1 }, zone: 'abyss_deep', reward: { recipes: [['recipe_high', 3]] } },
    { id: 'sm_umbra', level: 58, min: 54, after: ['sm_hollow'], w: 3, title: 'The Devourer', text: 'Umbra the Devourer drifts through Shadowmere now and then. Only the strongest parties live through it; the unique things it carries are the best there are.', goal: { kind: 'kill', type: 'umbra', count: 1 }, reward: { recipes: [['recipe_high', 3]] } },
    { id: 'sm_perfect', level: 58, after: ['sm_upgrade'], w: 1, title: 'Perfection', text: 'Seven steps is as far as any anvil goes. Bring something of yours to +7.', goal: { kind: 'upgrade', plus: 7, count: 1 } },
  ]),
];

export const QUEST_BY_ID = Object.fromEntries(QUESTS.map((q) => [q.id, q]));

// Monster families for quests (a type not listed is its own family).
export const FAMILY = {
  slime: 'slime', slime_blue: 'slime', slime_red: 'slime', slime_frost: 'slime', slime_glacial: 'slime', slime_cinder: 'slime', slime_void: 'slime',
  bandit: 'bandit', cultist: 'cultist',
  skeleton_minion: 'skeleton', skeleton_warrior: 'skeleton', skeleton_rogue: 'skeleton', skeleton_mage: 'skeleton', bone_guard: 'skeleton',
  frost_scout: 'frostborn', frost_raider: 'frostborn', raider_berserker: 'frostborn', ice_witch: 'frostborn', frost_archer: 'frostborn',
  ash_bandit: 'ashen', cinder_cultist: 'ashen', ash_knight: 'ashen', molten_brute: 'ashen', pyre_archer: 'ashen',
  bog_lurker: 'shade', night_stalker: 'shade', shadow_archer: 'shade', death_knight: 'shade', wraith: 'shade',
  dread_skeleton: 'dread', dread_minion: 'dread',
};
export const familyOf = (type) => FAMILY[type] || type;
export const FAMILY_LABEL = { slime: 'Slimes', bandit: 'Bandits', cultist: 'Cultists', skeleton: 'Skeletons', frostborn: 'Frostborn', ashen: 'Ashen foes', shade: 'Shades', dread: 'Dread dead' };
